version: '3.8'

services:
    api:
        container_name: api
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${PORT}:${PORT}
            - 9229:9229      
        env_file:
            - .env.docker.local
        networks:
            - codesupport-api
        depends_on:
            - postgres
        restart: unless-stopped
    postgres:
        container_name: postgres
        image: postgres:12
        networks:
            - codesupport-api
        environment:
            POSTGRES_PASSWORD: ruv2cyHT4H78BVzK7b4DnBAHJR8dG4fG
            POSTGRES_USER: admin
            POSTGRES_DB: codesupport-api
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
networks:
  codesupport-api:
volumes:
  pgdata: